[package]
name = "notes"
version = "0.1.0"
edition = "2021"

[lib]
name = "notes"
path = "src/lib/mod.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
humantime = "2.0.1"
