version: '3.6'

services:
  smartbrain-backend:
    container_name: backend
    #image node:18-alpine - not needed since it's already in the Dockerfile
    build: ./ # Run the Image Build Steps
    command: npm start
    working_dir: /app
#    links: # This will link the containers. HOWEVER this is no longer needed. Depecrated
#      - postgres
    ports:
      - "3000:3000" # Binds container ports to localhost. Make sure you pass in the --service-ports flag when running docker compose
    volumes: # this allows access to the file system in the container
      - .:/app # we're mapping our directory to the working directory in the container
      - /app/node_modules # Need to explicitly map node_modules as well
#  postgres:
#    build: ./postgres
#    enviornment: # sets the evn variables for the docker
#      POSTGRES_USER: admin
#      POSTGRES_PASSWORD: secret
#      POSTGRES_DB: smartbrain
#      POSTGRES_HOST: postgres
#    ports:
#      - 5432:5432
